language: node_js

node_js:
  - node

install: 
  - npm install

before_script:
  - npm run build

script:
  - npm run cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"